services:
  postgresql:
    image: "postgres:alpine3.19"
    container_name: "pv_tool_postgresql"
    env_file:
      - .env
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=${DATABASE_NAME}"
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME} -h localhost -p 5432" ]
      start_period: 5s
      interval: 10s
      timeout: 5s
  redis-cache:
    image: redis:alpine3.19
    hostname: redis-cache
    container_name: pv_tool_redis
    restart: on-failure
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - cache:/data
    networks:
      - default

  # flower:
  #   image: mher/flower:2.0
  #   container_name: pv_tool_flower
  #   command: celery flower --broker=redis://redis-cache:6379/0 --port=5555
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis-cache
  #   networks:
  #     - default

networks:
  default:
    name: "pv_tool"
    driver: bridge

volumes:
  postgresql:
    name: "pv_tool_postgresql"
  cache:
    name: "pv_tool_redis"
