"""empty message

Revision ID: b705cf815f5a
Revises: 1fc78ac2bc24
Create Date: 2025-08-18 15:06:20.393348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b705cf815f5a'
down_revision = '1fc78ac2bc24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_reporting_manager_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'reporting_manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reporting_manager_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_reporting_manager_id_fkey'), 'users', 'users', ['reporting_manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
