"""empty message

Revision ID: 99e56eff299d
Revises: da9f75be36c9
Create Date: 2025-08-12 02:01:18.200898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e56eff299d'
down_revision = 'da9f75be36c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'clients', 'media', ['media_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'user_role_link', 'users', ['user_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'user_role_link', 'clients', ['client_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'user_role_link', 'roles', ['role_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'user_type', 'clients', ['client_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'users', 'user_type', ['user_type_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key(None, 'users', 'users', ['reporting_manager_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'user_type', type_='foreignkey')
    op.drop_constraint(None, 'user_role_link', type_='foreignkey')
    op.drop_constraint(None, 'user_role_link', type_='foreignkey')
    op.drop_constraint(None, 'user_role_link', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    # ### end Alembic commands ###
