"""empty message

Revision ID: bb6527c5e4d2
Revises: c05c17090221
Create Date: 2025-08-05 16:11:09.195754

"""
from alembic import op
import sqlalchemy as sa

from migrations.seeder import sql_for_tenant, sql_for_tenant_users


# revision identifiers, used by Alembic.
revision = 'bb6527c5e4d2'
down_revision = 'c05c17090221'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('secret_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('deleted_by', sa.String(), nullable=True, comment='User ID who soft deleted this record'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('microsoft_credentials_config',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('config', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('deleted_by', sa.String(), nullable=True, comment='User ID who soft deleted this record'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('microsoft_mail_box_config',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('app_password', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('app_password_expired_at', sa.DateTime(), nullable=True),
    sa.Column('company_emails', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('subject_lines', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('last_execution', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('deleted_by', sa.String(), nullable=True, comment='User ID who soft deleted this record'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_users',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('deleted_by', sa.String(), nullable=True, comment='User ID who soft deleted this record'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id')
    )

    op.execute(sql_for_tenant)
    op.execute(sql_for_tenant_users)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_users')
    op.drop_table('microsoft_mail_box_config')
    op.drop_table('microsoft_credentials_config')
    op.drop_table('tenant')
    # ### end Alembic commands ###
