"""empty message

Revision ID: a386e3532f96
Revises: 20250101_001
Create Date: 2025-07-31 13:02:12.913852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a386e3532f96'
down_revision = '20250101_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_audit', sa.Column('document_intake_history_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_extraction_audit_document_intake_id'), table_name='extraction_audit')
    op.drop_constraint(op.f('fk_extraction_audit_document_intake_id'), 'extraction_audit', type_='foreignkey')
    op.create_foreign_key(None, 'extraction_audit', 'document_intake_history', ['document_intake_history_id'], ['id'])
    op.drop_column('extraction_audit', 'document_intake_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_audit', sa.Column('document_intake_id', sa.VARCHAR(length=26), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'extraction_audit', type_='foreignkey')
    op.create_foreign_key(op.f('fk_extraction_audit_document_intake_id'), 'extraction_audit', 'document_intake_history', ['document_intake_id'], ['id'])
    op.create_index(op.f('ix_extraction_audit_document_intake_id'), 'extraction_audit', ['document_intake_id'], unique=False)
    op.drop_column('extraction_audit', 'document_intake_history_id')
    # ### end Alembic commands ###
