"""empty message

Revision ID: 1fc78ac2bc24
Revises: 77f144577bf2
Create Date: 2025-08-18 13:54:33.960587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc78ac2bc24'
down_revision = '77f144577bf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_active')
    # ### end Alembic commands ###
