"""empty message

Revision ID: e821e98c9475
Revises: 9b46647efc81
Create Date: 2025-08-05 13:26:48.611149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e821e98c9475'
down_revision = '9b46647efc81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_intake_history', sa.Column('email_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_intake_history', 'email_body')
    # ### end Alembic commands ###
