"""empty message

Revision ID: dbd05e482320
Revises: b705cf815f5a
Create Date: 2025-08-19 01:16:17.670491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd05e482320'
down_revision = 'b705cf815f5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('module_permission_link_client_id_fkey'), 'module_permission_link', type_='foreignkey')
    op.drop_column('module_permission_link', 'client_id')
    op.drop_constraint(op.f('modules_client_id_fkey'), 'modules', type_='foreignkey')
    op.drop_column('modules', 'client_id')
    op.drop_constraint(op.f('permissions_client_id_fkey'), 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'client_id')
    op.drop_constraint(op.f('role_module_permission_link_client_id_fkey'), 'role_module_permission_link', type_='foreignkey')
    op.drop_column('role_module_permission_link', 'client_id')
    op.drop_constraint(op.f('roles_client_id_fkey'), 'roles', type_='foreignkey')
    op.drop_column('roles', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('roles_client_id_fkey'), 'roles', 'clients', ['client_id'], ['id'])
    op.add_column('role_module_permission_link', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('role_module_permission_link_client_id_fkey'), 'role_module_permission_link', 'clients', ['client_id'], ['id'])
    op.add_column('permissions', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('permissions_client_id_fkey'), 'permissions', 'clients', ['client_id'], ['id'])
    op.add_column('modules', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('modules_client_id_fkey'), 'modules', 'clients', ['client_id'], ['id'])
    op.add_column('module_permission_link', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('module_permission_link_client_id_fkey'), 'module_permission_link', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
