"""empty message

Revision ID: cf6d2f5f1f68
Revises: dbd05e482320
Create Date: 2025-08-19 22:14:44.341010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf6d2f5f1f68'
down_revision = 'dbd05e482320'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('microsoft_credentials_config_tenant_id_fkey'), 'microsoft_credentials_config', type_='foreignkey')
    op.drop_column('microsoft_credentials_config', 'tenant_id')
    op.add_column('microsoft_mail_box_config', sa.Column('client_id', sa.String(), nullable=False))
    op.add_column('microsoft_mail_box_config', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('microsoft_mail_box_config_tenant_id_fkey'), 'microsoft_mail_box_config', type_='foreignkey')
    op.create_foreign_key(None, 'microsoft_mail_box_config', 'clients', ['client_id'], ['id'], ondelete='cascade')
    op.drop_column('microsoft_mail_box_config', 'company_emails')
    op.drop_column('microsoft_mail_box_config', 'end_date')
    op.drop_column('microsoft_mail_box_config', 'start_date')
    op.drop_column('microsoft_mail_box_config', 'subject_lines')
    op.drop_column('microsoft_mail_box_config', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microsoft_mail_box_config', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('microsoft_mail_box_config', sa.Column('subject_lines', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('microsoft_mail_box_config', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('microsoft_mail_box_config', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('microsoft_mail_box_config', sa.Column('company_emails', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'microsoft_mail_box_config', type_='foreignkey')
    op.create_foreign_key(op.f('microsoft_mail_box_config_tenant_id_fkey'), 'microsoft_mail_box_config', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('microsoft_mail_box_config', 'is_active')
    op.drop_column('microsoft_mail_box_config', 'client_id')
    op.add_column('microsoft_credentials_config', sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('microsoft_credentials_config_tenant_id_fkey'), 'microsoft_credentials_config', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
