"""empty message

Revision ID: 8f12ac04c7f0
Revises: 773269fddbeb
Create Date: 2025-08-07 16:51:27.988565

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8f12ac04c7f0"
down_revision = "773269fddbeb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_number_configurations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("separator", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "case_number_components",
        sa.Column("config_id", sa.String(), nullable=False),
        sa.Column("component_type", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("prompt", sa.String(length=255), nullable=True),
        sa.Column("ordering", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["config_id"], ["case_number_configurations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "case_sequence_trackers",
        sa.Column("config_id", sa.String(), nullable=False),
        sa.Column("year_month", sa.String(length=6), nullable=False),
        sa.Column("year", sa.String(length=4), nullable=False),
        sa.Column("current_value", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["config_id"], ["case_number_configurations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("config_id", "year", name="uq_tracker_config_year"),
        sa.UniqueConstraint("config_id", "year_month", name="uq_tracker_config_month"),
    )
    op.create_table(
        "cases",
        sa.Column("case_number", sa.String(length=255), nullable=False),
        sa.Column("config_id", sa.String(), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["config_id"], ["case_number_configurations.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cases")
    op.drop_table("case_sequence_trackers")
    op.drop_table("case_number_components")
    op.drop_table("case_number_configurations")
    # ### end Alembic commands ###
