"""empty message

Revision ID: 9e42255ca8c1
Revises: 773269fddbeb
Create Date: 2025-08-07 23:30:14.807670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e42255ca8c1'
down_revision = '773269fddbeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lookup_model',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('lookup_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('deleted_by', sa.String(), nullable=True, comment='User ID who soft deleted this record'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_model_name'), 'lookup_model', ['name'], unique=True)
    op.create_index(op.f('ix_lookup_model_slug'), 'lookup_model', ['slug'], unique=True)
    op.create_table('lookup_values_model',
    sa.Column('lookup_model_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('e2b_code_r2', sa.String(length=100), nullable=True),
    sa.Column('e2b_code_r3', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True, comment='User ID who created this record'),
    sa.Column('updated_by', sa.String(), nullable=True, comment='User ID who last updated this record'),
    sa.Column('deleted_by', sa.String(), nullable=True, comment='User ID who soft deleted this record'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lookup_model_id'], ['lookup_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lookup_model_id', 'name', name='uq_lookup_model_name')
    )
    op.create_index(op.f('ix_lookup_values_model_name'), 'lookup_values_model', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lookup_values_model_name'), table_name='lookup_values_model')
    op.drop_table('lookup_values_model')
    op.drop_index(op.f('ix_lookup_model_slug'), table_name='lookup_model')
    op.drop_index(op.f('ix_lookup_model_name'), table_name='lookup_model')
    op.drop_table('lookup_model')
    # ### end Alembic commands ###
