"""empty message

Revision ID: c05c17090221
Revises: e821e98c9475
Create Date: 2025-08-05 13:45:02.449316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05c17090221'
down_revision = 'e821e98c9475'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_agent', sa.Column('preferred_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_agent', 'preferred_model')
    # ### end Alembic commands ###
