"""empty message

Revision ID: 9b46647efc81
Revises: a386e3532f96
Create Date: 2025-07-31 13:15:22.111744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b46647efc81'
down_revision = 'a386e3532f96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_audit', sa.Column('document_intake_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('extraction_audit_document_intake_history_id_fkey'), 'extraction_audit', type_='foreignkey')
    op.create_foreign_key(None, 'extraction_audit', 'document_intake_history', ['document_intake_id'], ['id'])
    op.drop_column('extraction_audit', 'document_intake_history_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extraction_audit', sa.Column('document_intake_history_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'extraction_audit', type_='foreignkey')
    op.create_foreign_key(op.f('extraction_audit_document_intake_history_id_fkey'), 'extraction_audit', 'document_intake_history', ['document_intake_history_id'], ['id'])
    op.drop_column('extraction_audit', 'document_intake_id')
    # ### end Alembic commands ###
